# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gpt2_from_scratch',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/gpt2_from_scratch',
                'lib_path': 'gpt2_from_scratch'},
  'syms': {'gpt2_from_scratch.core': {'gpt2_from_scratch.core.foo': ('core.html#foo', 'gpt2_from_scratch/core.py')}}}
